# Generated by Django 5.1.4 on 2024-12-19 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthInfo', '0002_alter_exerciserecord_endtime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exerciserecord',
            old_name='CalorieCost',
            new_name='calorie_cost',
        ),
        migrations.RenameField(
            model_name='exerciserecord',
            old_name='EndTime',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='exerciserecord',
            old_name='ExerciseId',
            new_name='exercise_id',
        ),
        migrations.RenameField(
            model_name='exerciserecord',
            old_name='StartTime',
            new_name='start_time',
        ),
        migrations.RenameField(
            model_name='exerciserecord',
            old_name='Type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='exerciserecord',
            old_name='UserId',
            new_name='user_id',
        ),
    ]
